#pragma once

#define NUM_NOTES 128
#define PROG_UNDEFINED 0xFF
#define UNKNOWN_TABLE -1
#define MIN_SONG_NUM 20

#define BPM_PER_FRAME 150

#define N_CHANNELS 2
#define STREAM_SAMPLERATE 48000
#define STREAM_BUF_SIZE 2048
