# Warning: Artificial Incompetence (AI) ahead...
name: Nightly Release

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-commits:
    name: Check for recent commits
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check for recent commits
        id: check-commits
        shell: bash
        run: |
          COMMITS=$(git log $(echo $(git describe --tags --abbrev=0 2> /dev/null && echo ..HEAD) | tr -d '[:blank:]') --format=%H)
          if [ -z "${COMMITS}" ]; then
            echo "No commits since last tag. Skipping."
            echo "has-new-commits=false" >> "${GITHUB_OUTPUT}"
          else
            echo "Found $(echo "$COMMITS" | wc -l) commit(s) since last tag."
            echo "has-new-commits=true" >> "${GITHUB_OUTPUT}"
          fi

    outputs:
      has-new-commits: ${{ steps.check-commits.outputs.has-new-commits }}

  build-check:
    name: Check Build
    needs: check-commits
    if: needs.check-commits.outputs.has-new-commits == 'true'
    uses: ./.github/workflows/build-windows.yml

  create-release:
    name: Create Release
    needs:
      - build-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Make tag
        id: make-tag
        run: |
          echo "tag-name=nightly/v$(date -u '+%Y%m%d')-${GITHUB_SHA}" >> "${GITHUB_OUTPUT}"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.make-tag.outputs.tag-name }}" \
            --prerelease \
            --title "Nightly agbplay ${GITHUB_REF_NAME} ($(date -u '+%Y-%m-%d'))" \
            --target "${GITHUB_SHA}"
    outputs:
      tag-name: ${{ steps.make-tag.outputs.tag-name }}

  build-release:
    name: Release Build Windows
    needs:
      - create-release
    uses: ./.github/workflows/build-windows.yml

  upload-release:
    name: Upload Release Binaries
    needs:
      - create-release
      - build-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build-release.outputs.artifact-name }}

      - name: Zip Build Artifacts
        shell: bash
        run: |
          zip -r "nightly-${{ needs.build-release.outputs.artifact-name }}-$(date -u '+%Y%m%d').zip" agbplay/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.create-release.outputs.tag-name }} nightly-*.zip
